apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: log-volume
          emptyDir: {} # Shared volume between main container and sidecar
      containers:
      # Main Backend Container
      - name: backend-main
        image: vonkacuga/nodejs-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/tradehelper"
        - name: LOG_FILE
          value: "/var/log/app/app.log"
        volumeMounts:
          - name: log-volume
            mountPath: /var/log/app

        # Sidecar Container: Fluent Bit
      - name: fluentbit-sidecar
        image: fluent/fluent-bit:latest
        volumeMounts:
          - name: log-volume
            mountPath: /var/log/app
        args:
          - /fluent-bit/bin/fluent-bit
          - -i
          - tail
          - -p
          - path=/var/log/app/app.log
          - -p
          - read_from_head=true
          - -o
          - stdout
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
